### ISSUE TITLE
Allow editing coordinates of points

### ISSUE THREAD

**Issue by jidanni** [Zverik/osmtags-editor#2]
Let's say I want to insert / move a node to a given exact x and y.

> Listing below provides the official geographical coordinates of the boundary points for the Lake Ontario and
Niagara River section. They are provided in the same datum as they were originally published with reference to the
source.
NAD83 
Point Latitude Longitude Source
TP 105 N 44...

I wish there were an expert mode, that would expose the coordinates as editable fields.

**Comment by 501Ghost** [comment]
That seems risky when nodes are part of ways. A single mistake could lead to highways that make a sharp turn to go straight into the middle of the ocean before making an even sharper turn to go back.

**Comment by jidanni** [comment]
Then maybe just allow adding a new node to the map with custom coordinates.
Then at least there is a way to put something somewhere, exactly.

**Comment by 501Ghost** [comment]
At some point you're just better off using iD/Rapid.

**Comment by Zverik** [comment]
Yes, for adding a node, https://level0.osmz.ru/ is much better suited while having the same simple UI. Sorry but this editor was made for fast editing, not creating things or even touching the geometry.
