### ISSUE TITLE
More variety in the changeset description

### ISSUE THREAD

**Issue by 501Ghost** [Zverik/osmtags-editor#6]
Current behaviour: Changeset descriptions always say: "_Changed tag ... of node/way/relation XXXXX_."

Suggestion: Split the description into "Added tag ... to / Changed tag ... of / Removed tag ... from node/way/relation XXXXX."

This should make it a lot clearer how certain tags were changed.

**Comment by Dimitar5555** [comment]
Or even better, we can have input field where we can change the text and add/remove/rearrange parameters. Possibly with a tick box "Remember for future edits".
