### ISSUE TITLE
Multiple lines in tag causes all but the first to be removed.

### ISSUE THREAD

**Issue by Colbertson** [Zverik/osmtags-editor#7]
If an object has multiple lines in a tag such as this inscription= it removes all but the first line.
https://www.osm.org/node/5905401051/history

**Comment by hb0nd** [comment]
just encountered this as well, had to revert a whole bunch :/

i think it'd make sense to keep tag:value pairs in cells, otherwise this sort of issue happens

**Comment by Zverik** [comment]
Will be fixed in 1.2.
